config/routes.rb
Rails.application.routes.draw do
  
  root to: "practices#index"

  resources :practices do
    collection do
      post :search
      get :search
    end
  end  

  resources :users do
    collection do
      get :line_login
      post :line_login
      get :auth
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/practice.rb
class Practice < ApplicationRecord
  # validates_numericality_of :games_played, :only_integer => true
  BAR_LIST = ["槓鈴", "啞鈴", "W槓", "機械式", "Cable", "史密斯", "壺鈴", "徒手"]
  BODY_TYPE = ["胸", "背","腿","肩膀","手臂"]
  MOVING_LIST={
    "胸":["上胸", "平胸", "下胸", "夾胸"],
    "背":["硬舉", "站立划船", "坐式划船", "滑輪下拉", "單槓"], 
    "腿":["深蹲", "羅馬尼亞", "股四頭抬腿", "股二頭夾腿", "內夾腿","外夾腿", "小腿蹬"],
    "肩膀":["肩推", "側飛鳥", "Face pull"], 
    "手臂":["二頭彎舉","錘式","繩索三頭", "三頭"],
    "核心": ["抬腿"]
  }
  MOVING_TOTAL_LIST= ["上胸", "平胸", "下胸", "夾胸","硬舉", "站立划船", "坐式划船", "滑輪下拉", "單槓",
      "深蹲", "羅馬尼亞", "股四頭抬腿", "股二頭夾腿", "內夾腿","外張腿", "小腿蹬",
    "肩推", "側飛鳥", "後三角", "斜方肌", "二頭彎舉","二頭錘式","繩索三頭", "三頭", "小臂"]
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/practices_controller.rb
class PracticesController < ApplicationController
  before_action :debug_info
  before_action :set_practice, only: [:show, :edit, :update, :destroy]
  before_action :today_practice, only:[:index, :create, :update, :destroy]
  def index
    # @test = Practice.select(:bar_type, :moving).distinct
  end

  def search
    if request.get?
      p "--------------"
      p params
      p "--------------"
      @search = []
      Practice.select(:bar_type, :moving).where(line_id: params[:source_user_id]).distinct.each_with_index do |select, idx| 
        @search.push ["#{select.bar_type}#{select.moving}", idx]
      end
      p @search
    else
      m = params[:month].to_i
      t = params[:traning].to_i
      line_id = params[:source_user_id]
      p "============================"
      p params
      p "============================"
      list = Practice.select(:bar_type, :moving).where(line_id: line_id).distinct[t]
      @practices = Practice.where("line_id = ? AND bar_type = ? AND moving = ? AND created_at >= ?", line_id, list.bar_type, list.moving, Time.now - m.months)
      p @practices
      respond_to do |format|
          format.html { redirect_to @practices, notice: 'Practice was successfully created.' }
          format.json { render :show, status: :created, location: @practices }
          format.line { render :search }
      end
    end
  end

  def show;  end

  def new
    @practice = Practice.new
  end
  
  def edit;  end

  def create
    @practice = Practice.new(practice_params)

    respond_to do |format|
      if @practice.save
        format.html { redirect_to @practice, notice: 'Practice was successfully created.' }
        format.json { render :show, status: :created, location: @practice }
        format.line { render :index }
      else
        format.html { render :new }
        format.json { render json: @practice.errors, status: :unprocessable_entity }
        format.line { render json: flex_text(@practice.errors.to_s) }
      end
    end
  end

  def update
    respond_to do |format|
      if @practice.update(practice_params)
        format.html { redirect_to @practice, notice: 'Practice was successfully updated.' }
        format.json { render :show, status: :ok, location: @practice }
        format.line { render :index }
      else
        format.html { render :edit }
        format.json { render json: @practice.errors, status: :unprocessable_entity }
        format.line { render json: flex_text(@practice.errors.to_s) }
      end
    end
  end

  def destroy
    @practice.destroy
    respond_to do |format|
      format.html { redirect_to practices_url, notice: 'Practice was successfully destroyed.' }
      format.json { head :no_content }
      format.line { render :index }
    end
  end

  private
    def today_practice
      @practices = Practice.where(line_id: params[:source_user_id], created_at: Time.zone.now.beginning_of_day..Time.zone.now.end_of_day).order("created_at DESC")
    end

    def set_practice
      @practice = Practice.find(params[:id])
    end

    def practice_params
      params.require(:practice).permit(:bar_type, :moving, :amount, :unit, :rest, :weight, :line_id)
    end

    def debug_info
      puts ""
      puts "=== kamigo debug info start ==="
      puts "platform_type: #{params[:platform_type]}"
      puts "source_type: #{params[:source_type]}"
      puts "source_group_id: #{params[:source_group_id]}"
      puts "source_user_id: #{params[:source_user_id]}"
      puts "=== kamigo debug info end ==="
      puts ""
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :debug_info
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  protect_from_forgery with: :null_session
  skip_before_action :verify_authenticity_token, only: [:line_login]
  http_basic_authenticate_with name: ENV["AUTH_NAME"], password: ENV["AUTH_PASSWORD"], except: [:line_login, :auth]

  def line_login
    if request.get?
      p params
      r = HTTParty.post("https://api.line.me/oauth2/v2.1/token",
        body:{
          grant_type: "authorization_code",
          code: params["code"],
          redirect_uri: ENV["LINE_LOGIN_URI"],
          client_id: ENV["LINE_LOGIN_ID"],
          client_secret: ENV["LINE_LOGIN_KEY"]
        }, headers: {"Content-Type": "application/x-www-form-urlencoded"})
        
        payload = JSON.parse(r.body)
        token = payload["id_token"]
        hmac_secret = params['state']
        decoded_token = JWT.decode(token, hmac_secret, nil, { algorithm: 'HS256' })
        u = decoded_token[0]
        User.find_or_create_by({email: u["email"], name: u["name"], picture: u["picture"], line_id: u["sub"]})
        redirect_to "https://line.me/R/ti/p/#{ENV['LINE_AT_ID']}"
    else
      redirect_to "https://access.line.me/oauth2/v2.1/authorize?response_type=code&client_id=#{ENV['LINE_LOGIN_ID']}&redirect_uri=#{ENV['LINE_LOGIN_URI']}&state=nostate&scope=profile%20openid%20email&nonce=123qwe"
    end
  end

  def auth;  end

  def index
    @users = User.all
  end

  def show;  end

  def new
    @user = User.new
  end

  def edit;  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        @users = User.all
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
        format.line { render :index }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
        format.line { render json: flex_text(@user.errors.to_s) }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        @users = User.all
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
        format.line { render :index }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
        format.line { render json: flex_text(@todo.errors.to_s) }
      end
    end
  end

  def destroy
    @user.destroy
    @users = User.all
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
      format.line { render :index }
    end
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:name, :name, :line_id, :picture)
    end

    def debug_info
      puts ""
      puts "=== kamigo debug info start ==="
      puts "platform_type: #{params[:platform_type]}"
      puts "source_type: #{params[:source_type]}"
      puts "source_group_id: #{params[:source_group_id]}"
      puts "source_user_id: #{params[:source_user_id]}"
      puts "=== kamigo debug info end ==="
      puts ""
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/practices_helper.rb
module PracticesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>MuscleMan</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <%= yield %>
</body>

</html>

app/views/practices/_form.html.erb
<%= form_with(model: practice, local: true) do |form| %>
<div class="body-field">
  <div class="field">
    類型<%= select :practice, :bar_type, Practice::BAR_LIST, {}, { class: 'select-field' } %>
  </div>

  <div class="field">
    動作<%= select :practice, :moving, Practice::MOVING_TOTAL_LIST, {}, { class: 'select-field' } %>
  </div>

  <div class="field">
    次數<%= select :practice, :amount, (1..25).to_a, {}, { class: 'select-field' } %>
  </div>

  <div class="field">
    組數<%= select :practice, :unit, (1..10).to_a, {}, { class: 'select-field' } %>
  </div>

  <div class="field">
    組間(分)<%= select :practice, :rest, (1.0..10.0).step(0.5).to_a, {}, { class: 'select-field' } %>
  </div>

  <div class="field">
    重量(公斤)<%= form.number_field :weight, class: "select-field"%>
  </div>

  <%= form.hidden_field :line_id, value: params[:source_user_id] %>

  <div class="actions">
    <%= form.submit '送出', class: "btn btn-primary actions-btn" %>
  </div>
</div>
<% end %>

app/views/practices/edit.html.erb
<h1>Editing Practice</h1>

<%= render 'form', practice: @practice %>

<%= link_to 'Show', @practice %> |
<%= link_to 'Back', practices_path %>

app/views/practices/edit.liff.erb
<% content_for :title, "更改訓練項目" %>
<%= render "/practices/form.html", practice: @practice %>

app/views/practices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Practices</h1>

<table>
  <thead>
    <tr>
      <th>Bar type</th>
      <th>Moving</th>
      <th>Amount</th>
      <th>weight</th>
      <th>Unit</th>
      <th>Rest</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @practices.each do |practice| %>
    <tr>
      <td><%= practice.bar_type %></td>
      <td><%= practice.moving %></td>
      <td><%= practice.amount %></td>
      <td><%= practice.weight %></td>
      <td><%= practice.unit %></td>
      <td><%= practice.rest %></td>
      <td><%= link_to 'Show', practice %></td>
      <td><%= link_to 'Edit', edit_practice_path(practice) %></td>
      <td><%= link_to 'Destroy', practice, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Practice', new_practice_path %>

app/views/practices/index.line.erb
<%= raw(Kamiflex.build(self) do
  bubble do
    body do
      horizontal_box do
        text "🏆", flex: 0, action: message_action("/")
        text "今日訓練", weight: "bold", margin: "sm"
        text " 🔍 ", align: "end", action: uri_action(liff_path(path: search_practices_path, liff_size: 'full')), color: "#0000ee"
        text "新增", align: "end", action: uri_action(liff_path(path: new_practice_path, liff_size: 'full')), color: "#0000ee"
      end
      separator
      if @practices.present?
        vertical_box margin: "lg" do
          horizontal_box margin: "lg" do
            text "項目", weight: "bold"
          end
          horizontal_box @practices, margin: "lg" do |practice|
            text "#{practice.bar_type}#{practice.moving}", action: message_action("GET /practices/#{practice.id}")
            text "❌", align: "end", action: message_action("DELETE /practices/#{practice.id}")
          end
        end
      else
        text "今天還沒有訓練內容哦", margin: "lg"
      end
    end
  end
end )%>

app/views/practices/new.html.erb
<h1>New Practice</h1>

<%= render 'form', practice: @practice %>

<%= link_to 'Back', practices_path %>

app/views/practices/new.liff.erb
<% content_for :title, "新增訓練項目" %>
<%= render "/practices/form.html", practice: @practice %>

app/views/practices/search.liff.erb
<% content_for :title, "查詢項目" %>

<%= form_for "moving", url: search_practices_path, method: :post do |form| %>

<% end %>

<%= form_tag search_practices_path, method: :post do %>
<div class="body-field">

  <div class="field">
    查詢前Ｎ個月
    <%= select_tag "month", options_for_select((1..24).to_a), { class: 'select-field' } %>
  </div>

  <div class="field">
    項目
    <%= select_tag "traning", options_for_select(@search), { class: 'select-field' } %>
  </div>

  <div class="actions">
    <%= submit_tag "送出", class: "btn btn-primary actions-btn" %>
  </div>
</div>

  
<% end %>

app/views/practices/search.line.erb
<%= raw(Kamiflex.build(self) do
  bubble do
    body do
      horizontal_box do
        text " 🍔 ", flex: 0, action: message_action("/")
        text "最近a訓練", weight: "bold", margin: "sm"
      end
      separator
      if @practices.present?
        vertical_box margin: "lg" do
          horizontal_box margin: "lg" do
            text "項目", weight: "bold"
            text "重量", weight: "bold"
            text "日期", weight: "bold"
          end
          horizontal_box @practices, margin: "lg" do |practice|
            text "#{practice.bar_type}#{practice.moving}", action: message_action("GET /practices/#{practice.id}")
            text practice.weight.blank? ? "-" : practice.weight.to_s, margin: "xs"      
            text practice.created_at.blank? ? "-" : practice.created_at.strftime('%y-%m-%d'), align: "end", margin: "xs"      
          end
        end
      else
        text "今天還沒有訓練內容哦", margin: "lg"
      end
    end
  end
end )%>

app/views/practices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Bar type:</strong>
  <%= @practice.bar_type %>
</p>

<p>
  <strong>Moving:</strong>
  <%= @practice.moving %>
</p>

<p>
  <strong>Weight:</strong>
  <%= @practice.weight %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @practice.amount %>
</p>

<p>
  <strong>Unit:</strong>
  <%= @practice.unit %>
</p>

<p>
  <strong>Rest:</strong>
  <%= @practice.rest %>
</p>

<%= link_to 'Edit', edit_practice_path(@practice) %> |
<%= link_to 'Back', practices_path %>

app/views/practices/show.line.erb
<%= raw(Kamiflex.build(self) do
  bubble do
    body do
      horizontal_box do
        text "🍔", flex: 0, action: message_action("/")
        text "訓練項目", weight: "bold", margin: "sm"
        text "修改", align: "end", action: uri_action(liff_path(path: edit_practice_path(@practice), liff_size: 'full' )), color: "#0000ee"
      end
      separator

      horizontal_box margin: "md" do
        vertical_box do
          text "類型", weight: "bold", margin: "xs"
          text "動作", weight: "bold", margin: "xs"
          text "重量(公斤)", weight: "bold", margin: "xs"
          text "次數", weight: "bold", margin: "xs"
          text "組數", weight: "bold", margin: "xs"
          text "組間(分)", weight: "bold", margin: "xs"
          text "建立時間", weight: "bold", margin: "xs"
        end
        vertical_box do
          #text @practice.id.blank? ? "-" : @practice.id.to_s, align: "end", margin: "xs"
          text @practice.bar_type.blank? ? "-" : @practice.bar_type.to_s, align: "end", margin: "xs"
          text @practice.moving.blank? ? "-" : @practice.moving.to_s, align: "end", margin: "xs"
          text @practice.weight.blank? ? "-" : @practice.weight.to_s, align: "end", margin: "xs"
          text @practice.amount.blank? ? "-" : @practice.amount.to_s, align: "end", margin: "xs"
          text @practice.unit.blank? ? "-" : @practice.unit.to_s, align: "end", margin: "xs"
          text @practice.rest.blank? ? "-" : @practice.rest.to_s, align: "end", margin: "xs"
          text @practice.created_at.blank? ? "-" : @practice.created_at.strftime('%Y-%m-%d'), align: "end", margin: "xs"
        end
      end
    end
  end
end )%>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :line_id %>
    <%= form.text_field :line_id %>
  </div>

  <div class="field">
    <%= form.label :picture %>
    <%= form.text_field :picture %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/auth.html.erb
<script>
  $.ajax({
    beforeSend: function (xhr) {
      xhr.setRequestHeader('X-CSRF-Token', $('meta[name="csrf-token"]').attr('content'))
    },
    url: "/users/line_login",
    method: "POST",
    data: {
      "no": "thing"
    },
    success: function (data) {
      console.log(data)
    }
  });
</script>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Line</th>
      <th>Picture</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
    <tr>
      <td><%= user&.name %></td>
      <td><%= user&.email %></td>
      <td><%= user&.line_id %></td>
      <td><%= image_tag(user&.picture, height: '128', width: '128') if user&.picture? %></td>
      <td><%= link_to 'Show', user %></td>
      <td><%= link_to 'Edit', edit_user_path(user) %></td>
      <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Line:</strong>
  <%= @user.line_id %>
</p>

<p>
  <strong>Picture:</strong>
  <%= @user.picture %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>